'use strict';

const LOCATIONS = [
  {
    name: 'Punjab',
    slug: 'punjab',
    province: 'Punjab',
    key_districts: ['Faisalabad', 'Lahore', 'Multan', 'Sahiwal', 'Gujranwala', 'Sheikhupura', 'Bahawalpur'],
    main_crops: ['Wheat', 'Cotton', 'Sugarcane', 'Rice', 'Maize'],
    farmers_count: '8.2 million',
    cultivated_area: '14.5 million hectares',
    top_diseases: ['Yellow Rust (Wheat)', 'Cotton Whitefly', 'Bollworm', 'Sugarcane Smut'],
    agri_context: 'Punjab is Pakistan\'s agricultural heartland, contributing 53% of national crop output. The province has two main seasons: Rabi (Oct–Apr) dominated by wheat, and Kharif (Apr–Oct) dominated by cotton, rice, and maize.',
    zarii_active: true,
    urdu_name: 'پنجاب',
    stats: { share_of_national_output: '53%', avg_wheat_yield: '2.8 t/ha', whitefly_risk: 'Critical (Multan/Bahawalpur)' },
  },
  {
    name: 'Sindh',
    slug: 'sindh',
    province: 'Sindh',
    key_districts: ['Sukkur', 'Hyderabad', 'Larkana', 'Mirpur Khas', 'Nawabshah', 'Jacobabad'],
    main_crops: ['Rice', 'Cotton', 'Mango', 'Sugarcane', 'Banana'],
    farmers_count: '3.4 million',
    cultivated_area: '5.8 million hectares',
    top_diseases: ['Bacterial Leaf Blight (Rice)', 'Mango Anthracnose', 'Cotton Whitefly', 'Rice Blast'],
    agri_context: 'Sindh produces 70% of Pakistan\'s rice and most of the country\'s mango export crop. The Indus flood plains provide year-round irrigation, making it highly productive but also susceptible to waterborne diseases.',
    zarii_active: true,
    urdu_name: 'سندھ',
    stats: { share_of_national_output: '28%', rice_share: '70% of Pakistan\'s rice', mango_export_rank: 'Top province' },
  },
  {
    name: 'Khyber Pakhtunkhwa',
    slug: 'khyber-pakhtunkhwa',
    province: 'KPK',
    key_districts: ['Peshawar', 'Mardan', 'Swat', 'Charsadda', 'Nowshera'],
    main_crops: ['Wheat', 'Maize', 'Tobacco', 'Fruits (Apple, Peach, Pear)', 'Sugarcane'],
    farmers_count: '2.1 million',
    cultivated_area: '2.1 million hectares',
    top_diseases: ['Wheat Loose Smut', 'Maize Borer', 'Apple Scab', 'Peach Leaf Curl'],
    agri_context: 'KPK is known for high-value fruit production, especially apples from Swat. The mountainous terrain creates microclimates with different disease pressures from the plains. Tobacco is a major cash crop in Mardan and Charsadda.',
    zarii_active: true,
    urdu_name: 'خیبر پختونخوا',
    stats: { apple_production: 'Leading province', tobacco_area: '60,000+ hectares', altitude_range: '300–5,000m' },
  },
  {
    name: 'Balochistan',
    slug: 'balochistan',
    province: 'Balochistan',
    key_districts: ['Quetta', 'Turbat', 'Khuzdar', 'Mastung', 'Pishin'],
    main_crops: ['Wheat', 'Apple', 'Grapes', 'Apricot', 'Pomegranate', 'Almonds'],
    farmers_count: '1.2 million',
    cultivated_area: '1.4 million hectares (mostly rain-fed)',
    top_diseases: ['Apple Scab', 'Powdery Mildew (Grapes)', 'Fusarium Wilt', 'Root Rot'],
    agri_context: 'Balochistan is Pakistan\'s largest province by area and relies primarily on rain-fed (barani) agriculture. It leads in apple and fruit production outside KPK. Extreme temperature swings and water scarcity shape disease patterns.',
    zarii_active: true,
    urdu_name: 'بلوچستان',
    stats: { area: 'Largest province (44% of Pakistan)', apple_orchards: '90,000+ hectares', water_stress: 'High — arid climate' },
  },
  {
    name: 'Faisalabad',
    slug: 'faisalabad',
    province: 'Punjab',
    key_districts: ['Faisalabad', 'Chiniot', 'Jhang', 'Toba Tek Singh'],
    main_crops: ['Wheat', 'Cotton', 'Sugarcane', 'Rice', 'Vegetables'],
    farmers_count: '650,000+',
    cultivated_area: '2.1 million hectares',
    top_diseases: ['Yellow Rust (Wheat)', 'Cotton Whitefly', 'Phytophthora Blight (Chili)'],
    agri_context: 'Faisalabad district is the agricultural research hub of Pakistan, home to AARI (Ayub Agricultural Research Institute) which develops disease-resistant varieties and pesticide recommendations. Yellow Rust pressure is monitored weekly here by federal plant protection teams.',
    zarii_active: true,
    urdu_name: 'فیصل آباد',
    stats: { aari_founded: '1962', rust_monitoring: 'Weekly AARI surveillance', wheat_area: '800,000+ hectares' },
  },
  {
    name: 'Multan',
    slug: 'multan',
    province: 'Punjab',
    key_districts: ['Multan', 'Lodhran', 'Vehari', 'Khanewal'],
    main_crops: ['Cotton', 'Wheat', 'Mango', 'Citrus', 'Vegetables'],
    farmers_count: '450,000+',
    cultivated_area: '1.6 million hectares',
    top_diseases: ['Cotton Whitefly (Critical)', 'Bollworm', 'Mango Anthracnose', 'Citrus Greening'],
    agri_context: 'Multan is the "City of Saints" and Pakistan\'s cotton capital. The district currently has the highest whitefly pressure in the country (1,840 farms affected, 312% above seasonal average as of May 2026). Mango orchards are significant in the eastern tehsils.',
    zarii_active: true,
    urdu_name: 'ملتان',
    stats: { whitefly_farms_affected: '1,840+', whitefly_trend: '+312% above average', mango_area: '200,000+ trees' },
  },
];

module.exports = { LOCATIONS };
