'use strict';

const { slug } = require('./ssrShell');

// ── Disease guides (proprietary data: AI diagnosis targets for Pakistani crops) ──
const DISEASE_GUIDES = [
  {
    slug: 'cotton-whitefly-pakistan',
    name: 'Cotton Whitefly',
    scientific: 'Bemisia tabaci',
    crop: 'Cotton',
    urdu: 'سفید مکھی',
    regions: ['Multan', 'Bahawalpur', 'Sahiwal', 'Rahim Yar Khan'],
    pressure: 'Critical',
    symptoms: 'Yellowing leaves, sticky honeydew deposits on undersides of leaves, sooty mold growth, stunted plant growth, and premature leaf drop. Infested cotton plants show silver or bronze sheen on leaf surfaces.',
    causes: 'Bemisia tabaci is a sap-sucking insect that feeds on phloem sap. Hot, dry weather above 35°C accelerates population growth. A single female can lay 100–300 eggs. Populations can increase 10-fold within 10 days under optimal conditions.',
    treatment: [
      { step: 1, action: 'Apply imidacloprid (Confidor 200 SL at 0.5 ml/L) or acetamiprid as a foliar spray — most effective within first 48 hours of detection.' },
      { step: 2, action: 'Use yellow sticky traps (5 per acre) for monitoring and mass-trapping adult whiteflies.' },
      { step: 3, action: 'Remove heavily infested leaves and burn them away from the field.' },
      { step: 4, action: 'Apply neem oil (5 ml/L) as an organic alternative or resistance-management rotation.' },
      { step: 5, action: 'Repeat spray after 7–10 days if population exceeds 10 nymphs per leaf.' },
    ],
    prevention: 'Plant resistant varieties (NIAB-878, CIM-598). Avoid excess nitrogen fertilizer which promotes soft leaf growth. Maintain field hygiene by removing crop debris after harvest. Introduce natural predators such as Encarsia formosa and lacewings.',
    economic_threshold: '10 nymphs per leaf or 5 adults per yellow sticky trap per 24 hours',
    season: 'June–October (peak July–September)',
    pkr_loss: '15,000–60,000 per acre in severe infestations',
    stats: [
      { label: 'Farms Affected (Punjab)', value: '1,840+' },
      { label: 'Avg Yield Loss', value: '30–60%' },
      { label: 'Peak Season', value: 'Jul–Sep' },
      { label: 'Treatment Window', value: '48 hrs' },
    ],
    faqs: [
      { q: 'How do I identify whitefly on cotton in Pakistan?', a: 'Look for tiny white flying insects under cotton leaves, sticky honeydew deposits, and black sooty mold on leaf surfaces. Shake a plant — if white insects fly up, that confirms whitefly infestation.' },
      { q: 'Which pesticide is best for cotton whitefly in Pakistan?', a: 'Imidacloprid (Confidor 200 SL) at 0.5 ml/L water is the most widely recommended by Pakistan\'s PCCC. Actara 25 WG (thiamethoxam) at 0.4 g/L is a second-line option. Rotate chemical groups to prevent resistance.' },
      { q: 'When should I spray for whitefly on cotton?', a: 'Spray as soon as you reach the economic threshold of 10 nymphs per leaf or 5 adults per sticky trap. Early morning or evening spraying is most effective as whiteflies are less active.' },
      { q: 'Is cotton whitefly contagious between fields?', a: 'Yes — adult whiteflies fly and can spread between adjacent fields. Coordinated spraying across multiple farms in an area is more effective than single-farm treatment.' },
    ],
  },
  {
    slug: 'wheat-yellow-rust-pakistan',
    name: 'Wheat Yellow Rust',
    scientific: 'Puccinia striiformis f. sp. tritici',
    crop: 'Wheat',
    urdu: 'گندم کا زرد زنگ',
    regions: ['Faisalabad', 'Gujranwala', 'Lahore', 'Sheikhupura', 'Sargodha'],
    pressure: 'High',
    symptoms: 'Bright yellow-orange pustules arranged in stripes along leaf veins. Infected leaves show powdery yellow-orange spore masses. Severe infections cause leaf shriveling and premature death. Green ear syndrome in late infections.',
    causes: 'Puccinia striiformis is an obligate biotroph that spreads via wind-borne urediniospores. Cool temperatures (5–15°C) with leaf wetness for 3–6 hours are ideal for infection. The disease can spread 500 km in 24 hours under favourable wind conditions.',
    treatment: [
      { step: 1, action: 'Apply propiconazole (Tilt 250 EC at 0.5 ml/L) or tebuconazole as foliar fungicide at first sign of pustules.' },
      { step: 2, action: 'Use Score 250 EC (difenoconazole at 0.5 ml/L) as an alternative if triazole resistance is suspected.' },
      { step: 3, action: 'Ensure thorough coverage of all leaf surfaces, especially lower leaves where rust initiates.' },
      { step: 4, action: 'Repeat spray 14–21 days later if conditions remain cool and humid.' },
    ],
    prevention: 'Plant rust-resistant varieties (Faisalabad-2008, NARC-2009, Pirsabak-15). Avoid early sowing before October 20 in Punjab which increases rust risk. Remove volunteer wheat plants between seasons.',
    economic_threshold: '5% leaf area infected on flag leaf, or visible pustules on upper 3 leaves',
    season: 'November–March (peak January–February)',
    pkr_loss: '10,000–40,000 per acre in untreated fields',
    stats: [
      { label: 'Farms Affected (Punjab)', value: '380+' },
      { label: 'Avg Yield Loss', value: '20–70%' },
      { label: 'Peak Season', value: 'Jan–Feb' },
      { label: 'Spray Efficacy', value: '85–95%' },
    ],
    faqs: [
      { q: 'How do I identify yellow rust on wheat in Pakistan?', a: 'Look for bright yellow-orange powdery stripes running parallel to leaf veins. When you rub an infected leaf, yellow-orange spore dust transfers to your fingers. This distinguishes it from brown rust which forms scattered pustules.' },
      { q: 'What fungicide works best for wheat yellow rust in Pakistan?', a: 'Propiconazole (Tilt 250 EC) is Pakistan\'s first-line recommendation. Score 250 EC (difenoconazole) is effective as a second option. Apply within 48 hours of pustule appearance for best results — delaying even 3 days reduces efficacy by 40%.' },
      { q: 'Can wheat yellow rust spread from one field to another?', a: 'Yes — P. striiformis spores travel by wind for hundreds of kilometers. A single infected field can spread spores across an entire district within days under favourable wind conditions.' },
      { q: 'What wheat varieties are resistant to yellow rust in Pakistan?', a: 'NARC-2009, Faisalabad-2008, Seher-2006, and Pirsabak-2015 show strong resistance. Punjab Seed Corporation releases updated resistance ratings annually — always confirm variety status before the growing season as new rust races emerge.' },
    ],
  },
  {
    slug: 'tomato-early-blight-pakistan',
    name: 'Tomato Early Blight',
    scientific: 'Alternaria solani',
    crop: 'Tomato',
    urdu: 'ٹماٹر کی ابتدائی جھلسا بیماری',
    regions: ['Peshawar', 'Nowshera', 'Mardan', 'Multan', 'Lahore'],
    pressure: 'High',
    symptoms: 'Dark brown to black lesions with concentric rings (target-board pattern) on older lower leaves. Yellow halo surrounds lesions. Affected leaves turn yellow and drop. Stem lesions form dark sunken cankers.',
    causes: 'Alternaria solani is a fungal pathogen that overwinters in infected plant debris and soil. Spores spread by wind and water splash. Warm temperatures (24–29°C) combined with high humidity (>90%) trigger disease. Nitrogen-deficient plants are highly susceptible.',
    treatment: [
      { step: 1, action: 'Apply mancozeb (Mancozeb 75 WP at 2 g/L) as protective spray before or at first symptom appearance.' },
      { step: 2, action: 'Use azoxystrobin + difenoconazole (Amistar Top) for curative treatment of established infections.' },
      { step: 3, action: 'Remove and destroy infected leaves immediately to reduce spore load.' },
      { step: 4, action: 'Avoid overhead irrigation — use drip irrigation where possible to keep foliage dry.' },
    ],
    prevention: 'Use certified disease-free seed. Maintain 60–75 cm plant spacing for airflow. Apply balanced NPK fertilizer — avoid nitrogen excess. Mulch soil surface to reduce splash dispersal from soil.',
    economic_threshold: '25% defoliation of lower leaves',
    season: 'Year-round in Pakistan; peak risk March–May and September–November',
    pkr_loss: '8,000–35,000 per acre',
    stats: [
      { label: 'Yield Loss Potential', value: '50–80%' },
      { label: 'Incubation Period', value: '3–5 days' },
      { label: 'Key Season', value: 'Mar–May' },
      { label: 'Treatment Cost', value: 'Rs 800–1,500/acre' },
    ],
    faqs: [
      { q: 'How do I identify early blight on tomatoes in Pakistan?', a: 'Look for circular dark lesions with concentric rings forming a "bulls-eye" pattern on older lower leaves. A yellow halo appears around each lesion. Early blight always starts on the oldest leaves and progresses upward.' },
      { q: 'What is the best fungicide for tomato early blight in Pakistan?', a: 'Mancozeb 75 WP (2 g/L) is the most affordable and widely available option. For curative treatment, Score 250 EC (difenoconazole at 0.5 ml/L) is more effective on established infections. Spray every 7–10 days during humid periods.' },
      { q: 'Is tomato early blight the same as late blight?', a: 'No. Early blight (Alternaria solani) forms target-board lesions starting on lower leaves. Late blight (Phytophthora infestans) causes water-soaked lesions with white fluffy growth on the undersides of leaves and spreads much faster. They require different fungicides.' },
    ],
  },
  {
    slug: 'mango-anthracnose-pakistan',
    name: 'Mango Anthracnose',
    scientific: 'Colletotrichum gloeosporioides',
    crop: 'Mango',
    urdu: 'آم کا اینتھراکنوز',
    regions: ['Multan', 'Rahim Yar Khan', 'Mirpur Khas', 'Hyderabad', 'Tando Allahyar'],
    pressure: 'Moderate',
    symptoms: 'Black to dark brown irregular spots on leaves, flowers, and fruits. Flower panicle blight causes total flower abortion. Fruit lesions are sunken, dark, and expand rapidly post-harvest. Infected fruits show "mummification" when disease is severe.',
    causes: 'Colletotrichum gloeosporioides overwinters in infected twigs and mummified fruits. Spores are splash-dispersed during rains. Warm (25–30°C) and wet conditions during flowering are the highest-risk period. Post-harvest infections cause major export losses.',
    treatment: [
      { step: 1, action: 'Apply carbendazim (0.1%) or thiophanate-methyl at bud burst, full bloom, and 2–3 weeks after fruit set.' },
      { step: 2, action: 'Use copper-based fungicides (copper oxychloride 0.3%) as a protective cover spray.' },
      { step: 3, action: 'Hot water treatment (52°C for 5 minutes) for harvested fruit to prevent post-harvest spread.' },
    ],
    prevention: 'Prune to improve canopy ventilation. Remove and burn mummified fruits and infected twigs. Apply pre-harvest copper spray 3 weeks before harvest. For export-grade fruit, begin sprays at flower bud initiation.',
    economic_threshold: '10% of flowers infected or visible lesions on developing fruitlets',
    season: 'March–June (flowering/fruiting period critical)',
    pkr_loss: '20,000–80,000 per acre in severe seasons',
    stats: [
      { label: 'Pakistan Mango Export Risk', value: '40% rejected' },
      { label: 'Critical Window', value: 'Flowering' },
      { label: 'Farms Affected (Sindh)', value: '180+' },
      { label: 'Treatment Sprays', value: '3–4/season' },
    ],
    faqs: [
      { q: 'How do I identify mango anthracnose in Pakistan?', a: 'Dark irregular spots appear on flowers, young fruit, and leaves. The most diagnostic sign is total blackening and death of flower panicles ("flower blight"). On fruit, lesions are sunken and dark brown with a water-soaked margin.' },
      { q: 'What fungicide is best for mango anthracnose in Pakistan?', a: 'Carbendazim (0.1%) is the most effective and widely used in Pakistan. Begin spraying at bud burst and repeat at 14-day intervals through fruit set. Copper oxychloride (0.3%) is a good preventive option and less likely to cause resistance.' },
      { q: 'Why does mango anthracnose get worse after harvest?', a: 'The fungus can be present on fruit skin as a latent (dormant) infection that activates as fruit ripens and defenses weaken. This is why post-harvest hot water treatment or fungicide dips are critical for export-quality mangoes.' },
    ],
  },
  {
    slug: 'rice-bacterial-leaf-blight-pakistan',
    name: 'Rice Bacterial Leaf Blight',
    scientific: 'Xanthomonas oryzae pv. oryzae',
    crop: 'Rice',
    urdu: 'چاول کی بیکٹیریائی پتہ جھلسا',
    regions: ['Gujranwala', 'Sialkot', 'Sheikhupura', 'Sukkur', 'Larkana'],
    pressure: 'Moderate',
    symptoms: 'Water-soaked yellowish stripe along leaf margins starting from tip. Lesions turn straw-colored as they expand. Bacterial ooze (milky droplets) visible on fresh lesions in early morning. Severe cases: complete leaf yellowing and wilting.',
    causes: 'Xanthomonas oryzae spreads through irrigation water, rain splash, and infected seed. Enters through leaf margins via hydathodes. Warm temperatures (25–34°C) and high humidity favour disease. Typhoons and flooding cause explosive outbreaks.',
    treatment: [
      { step: 1, action: 'Apply copper-based bactericides (copper oxychloride 0.3%) as foliar spray — no specific curative bactericide is registered in Pakistan.' },
      { step: 2, action: 'Drain fields and avoid flood irrigation during active infection periods.' },
      { step: 3, action: 'Increase potassium fertilizer — potassium strengthens cell walls and reduces bacterial penetration.' },
    ],
    prevention: 'Use certified disease-free seed or treat seed with streptomycin sulfate (0.025%) before sowing. Plant resistant IRRI varieties (IR-64, Super Basmati with BLB resistance). Avoid excess nitrogen. Maintain proper drainage.',
    economic_threshold: 'Visible symptoms before heading stage — treat immediately',
    season: 'July–October (transplanting to heading)',
    pkr_loss: '10,000–45,000 per acre in vulnerable varieties',
    stats: [
      { label: 'Farms Affected (Sindh)', value: '95+' },
      { label: 'Yield Loss', value: '20–50%' },
      { label: 'Key Stage', value: 'Tillering' },
      { label: 'Season', value: 'Jul–Oct' },
    ],
    faqs: [
      { q: 'How do I identify bacterial leaf blight on rice in Pakistan?', a: 'Look for yellowish water-soaked lesions starting at leaf tips and margins, spreading downward. In the morning, you may see milky bacterial ooze (dried as white-yellow beads) on fresh lesions. This is the most distinctive diagnostic sign.' },
      { q: 'Is there a specific bactericide for rice BLB in Pakistan?', a: 'No curative bactericide is currently registered for rice BLB in Pakistan. Copper-based products (copper oxychloride 0.3%) provide some suppression. The most effective management is through resistant varieties and cultural practices.' },
      { q: 'What rice varieties are resistant to BLB in Pakistan?', a: 'Basmati-515, Super Basmati (selected lines), and IRRI-derived varieties like IR-64 show moderate to good resistance. Kainat and Shaheen Basmati are highly susceptible — avoid in flood-prone or BLB-endemic areas.' },
    ],
  },
  {
    slug: 'cotton-bollworm-pakistan',
    name: 'Cotton Pink Bollworm',
    scientific: 'Pectinophora gossypiella',
    crop: 'Cotton',
    urdu: 'گلابی سنڈی',
    regions: ['Sahiwal', 'Okara', 'Khanewal', 'Lodhran', 'Vehari'],
    pressure: 'High',
    symptoms: 'Entry holes in cotton squares and bolls. Damaged squares fail to open ("flared squares"). Internal feeding on lint and seeds. Stained, underdeveloped lint. Pink-colored larvae (4th instar) visible inside opened bolls.',
    causes: 'Pectinophora gossypiella overwinters as diapausing larvae in stored seed or soil. Moths emerge in spring and lay eggs in squares. Larvae bore directly into bolls. Can complete 4–5 generations per season in Pakistan.',
    treatment: [
      { step: 1, action: 'Apply lambda-cyhalothrin (Karate 2.5 EC at 0.8 ml/L) or cypermethrin at 5% square infestation level.' },
      { step: 2, action: 'Use pheromone traps (3 per acre) for monitoring — treat when catch exceeds 8 moths/trap/night.' },
      { step: 3, action: 'Spinosad-based biopesticide as resistance management rotation with synthetic pyrethroids.' },
    ],
    prevention: 'Destroy crop residues immediately after harvest. Gin seed cotton promptly — delayed ginning allows larvae to complete development. Use Bt cotton varieties where available. Avoid staggered planting which creates continuous host availability.',
    economic_threshold: '5% infested squares, or 5 moths per pheromone trap per night',
    season: 'July–November',
    pkr_loss: '12,000–50,000 per acre',
    stats: [
      { label: 'Farms Affected (Punjab)', value: '420+' },
      { label: 'Generations/Season', value: '4–5' },
      { label: 'Yield Loss', value: '15–40%' },
      { label: 'Treatment Window', value: '5% squares' },
    ],
    faqs: [
      { q: 'How do I identify pink bollworm on cotton?', a: 'Look for small entry holes in cotton squares (flower buds) and bolls. Cut open damaged bolls to find pink-colored caterpillars feeding inside. "Flared squares" — squares that open abnormally without blooming — are a strong diagnostic sign.' },
      { q: 'What is the best spray for cotton bollworm in Pakistan?', a: 'Lambda-cyhalothrin (Karate 2.5 EC) is widely used and effective. Rotate with cypermethrin or spinosad to manage resistance. Always spray in the evening when beneficial insects are less active.' },
    ],
  },
];

// ── Pesticide catalog (live from DB — supplement with rich content) ──
const PESTICIDE_CONTENT = {
  'Antracol 70 WP':  { description: 'Broad-spectrum protective fungicide. Propineb (70%) prevents spore germination. Highly effective against early blight, downy mildew, and leaf spots on vegetables and fruits. Low resistance risk due to multi-site mode of action.', crops: ['Tomato', 'Potato', 'Mango', 'Grape', 'Chilli'], when: 'Apply preventively before disease appears or at first sign of symptoms. Repeat every 7–10 days during wet weather.' },
  'Confidor 200 SL': { description: 'Systemic insecticide (imidacloprid 200 g/L). Absorbed through roots and leaves. Controls sucking pests including whitefly, aphids, thrips, and jassids. Neonicotinoid class — effective for 2–3 weeks.', crops: ['Cotton', 'Tomato', 'Brinjal', 'Mango', 'Citrus'], when: 'Apply at first detection of infestation. Do not apply to flowering crops to protect pollinators.' },
  'Actara 25 WG':    { description: 'Thiamethoxam (25%) systemic insecticide — newer neonicotinoid with excellent root uptake. Fast knockdown and long residual activity. Controls whitefly, aphids, mealybugs, and rice BPH.', crops: ['Cotton', 'Rice', 'Vegetables', 'Fruit trees'], when: 'Use as seed treatment, drench, or foliar spray. Especially effective as soil drench for persistent control.' },
  'Ridomil Gold MZ': { description: 'Combination fungicide: metalaxyl-M (4%) + mancozeb (64%). Metalaxyl-M is absorbed systemically to protect new growth; mancozeb provides broad-spectrum surface protection. Essential for downy mildew and Phytophthora.', crops: ['Tomato', 'Potato', 'Cucumber', 'Grapes'], when: 'Apply preventively before wet conditions. Effective at 2 g/L water every 10–14 days.' },
  'Karate 2.5 EC':   { description: 'Lambda-cyhalothrin (2.5%) synthetic pyrethroid. Fast knockdown against chewing and sucking insects. Repellent effect keeps insects off treated surfaces for 5–7 days. Very broad spectrum.', crops: ['Cotton', 'Wheat', 'Vegetables', 'Maize', 'Rice'], when: 'Apply at economic threshold. Evening application preferred — cooler temperatures extend activity. Avoid during flowering.' },
  'Sarbex 5G':       { description: 'Carbofuran 5% granular soil insecticide. Absorbed through roots to control soil pests and sucking insects systemically. Controls termites, cutworms, rootworms, and stem borers.', crops: ['Sugarcane', 'Maize', 'Vegetables', 'Rice'], when: 'Apply at planting or transplanting by incorporating into soil. Do not apply to wet soils or near water bodies.' },
  'Mancozeb 75 WP':  { description: 'Mancozeb (75%) broad-spectrum protectant fungicide. Multi-site mode of action provides very low resistance risk. Excellent for early blight, late blight, downy mildew, and leaf spots across all crops. Most cost-effective fungicide in Pakistan.', crops: ['Tomato', 'Potato', 'Cotton', 'Mango', 'Onion', 'Chilli'], when: 'Apply preventively every 7–14 days. Most effective before disease establishes. Can be tank-mixed with most insecticides.' },
  'Score 250 EC':    { description: 'Difenoconazole (250 g/L) DMI fungicide (triazole class). Curative and preventive activity against Alternaria, Fusarium, Septoria, rusts, and powdery mildew. Absorbed and translocated within plant tissue.', crops: ['Wheat', 'Tomato', 'Potato', 'Mango', 'Rice'], when: 'Apply at first symptom appearance. Curative within 48–72 hours of infection. Repeat after 14–21 days.' },
  'Urea (46% N)':    { description: 'Pakistan\'s most widely used nitrogen fertilizer. 46% elemental nitrogen as amide. Rapidly converted to ammonium and nitrate in soil. Essential for vegetative growth, protein synthesis, and green color.', crops: ['Wheat', 'Rice', 'Cotton', 'Maize', 'Sugarcane', 'Vegetables'], when: 'Apply in split doses: 1/3 at sowing, 1/3 at tillering/vegetative, 1/3 at reproductive stage. Avoid surface application in rain — use incorporation.' },
  'DAP':             { description: 'Diammonium phosphate (18% N, 46% P2O5). Primary phosphorus fertilizer in Pakistan. Phosphorus drives root development, flowering, and seed formation. Also provides nitrogen boost at germination.', crops: ['Wheat', 'Rice', 'Cotton', 'Maize', 'Vegetables', 'Oilseeds'], when: 'Apply entire dose at or before sowing, incorporated into soil. Phosphorus is immobile — surface application reduces efficacy by 30–50%.' },
};

// ── Pakistan farming regions ──
const FARMING_REGIONS = [
  {
    slug: 'punjab-farmers',
    name: 'Punjab',
    urdu: 'پنجاب',
    area_mha: 20.6,
    main_crops: ['Wheat', 'Cotton', 'Rice', 'Sugarcane', 'Maize'],
    key_districts: ['Faisalabad', 'Lahore', 'Multan', 'Gujranwala', 'Sahiwal', 'Bahawalpur', 'Sargodha'],
    active_diseases: ['Yellow Rust on Wheat', 'Whitefly on Cotton', 'Bollworm on Cotton', 'Early Blight on Tomato'],
    farmer_count: '8.2 million',
    description: 'Punjab is Pakistan\'s agricultural heartland, contributing 80% of national wheat production and 65% of cotton output. The province spans three major agro-climatic zones: the northern foothills, the central canal-irrigated plains, and the southern arid zone.',
    soil_types: 'Alluvial loam (canal-irrigated belt), sandy loam (Cholistan fringe), clay loam (Pothohar plateau)',
    avg_farm_size: '4.2 acres',
    irrigation: 'Canal irrigation (Indus basin canals) and groundwater tube wells',
    challenges: 'Water scarcity (groundwater depletion in central Punjab), cotton whitefly resistance to insecticides, wheat rust race evolution, increasing heat stress during grain fill.',
  },
  {
    slug: 'sindh-farmers',
    name: 'Sindh',
    urdu: 'سندھ',
    area_mha: 14.9,
    main_crops: ['Cotton', 'Rice', 'Wheat', 'Sugarcane', 'Mango', 'Banana'],
    key_districts: ['Hyderabad', 'Sukkur', 'Mirpur Khas', 'Larkana', 'Nawabshah', 'Badin'],
    active_diseases: ['Anthracnose on Mango', 'BLB on Rice', 'Whitefly on Cotton', 'Downy Mildew on Grape'],
    farmer_count: '3.1 million',
    description: 'Sindh is Pakistan\'s second-largest agricultural province, dominant in rice (Basmati and IRRI), mango production (Sindhri variety), and sugarcane. The Indus delta and lower Sindh plains are among Pakistan\'s most fertile farming areas.',
    soil_types: 'Alluvial clay (Indus delta), saline-alkaline soils (Thar fringe), loamy soils (central Sindh)',
    avg_farm_size: '5.8 acres',
    irrigation: 'Indus river barrage system; heavy monsoon dependence in lower Sindh',
    challenges: 'Waterlogging and salinity affecting 40% of farmland, irregular monsoon, mango anthracnose export quality issues, post-harvest losses exceeding 35%.',
  },
  {
    slug: 'kpk-farmers',
    name: 'Khyber Pakhtunkhwa',
    urdu: 'خیبر پختونخوا',
    area_mha: 3.5,
    main_crops: ['Wheat', 'Maize', 'Tobacco', 'Vegetables', 'Fruit (apple, peach)'],
    key_districts: ['Peshawar', 'Nowshera', 'Mardan', 'Swat', 'Chitral', 'Dir'],
    active_diseases: ['Early Blight on Tomato', 'Powdery Mildew on Vegetables', 'Fire Blight on Apple'],
    farmer_count: '1.4 million',
    description: 'KPK\'s agriculture ranges from irrigated tobacco and vegetable production in the Vale of Peshawar to high-altitude fruit orchards in Swat, Chitral, and Dir. The province produces 90% of Pakistan\'s tobacco crop.',
    soil_types: 'Loamy to clay loam (Peshawar valley), rocky mountainous soils (upper KPK)',
    avg_farm_size: '2.1 acres',
    irrigation: 'River lift irrigation, hill torrents, glacial meltwater in upper districts',
    challenges: 'Small fragmented landholdings, limited access to agrochemical dealers, climate variability, high vegetable disease pressure during monsoon.',
  },
  {
    slug: 'balochistan-farmers',
    name: 'Balochistan',
    urdu: 'بلوچستان',
    area_mha: 6.2,
    main_crops: ['Wheat', 'Fruits (apple, grape, pomegranate, date)', 'Vegetables', 'Cumin'],
    key_districts: ['Quetta', 'Turbat', 'Khuzdar', 'Mastung', 'Kalat'],
    active_diseases: ['Powdery Mildew on Grapes', 'Fire Blight on Apple', 'Alternaria on Pomegranate'],
    farmer_count: '0.8 million',
    description: 'Balochistan is Pakistan\'s largest province by area and the primary producer of export-quality fruits. Apple orchards of Mastung and Kalat, grape vineyards of Quetta, and date palms of Turbat are globally recognized.',
    soil_types: 'Sandy loam to clay loam (valleys), rocky arid soils (highlands), alluvial (Indus fringe)',
    avg_farm_size: '8.4 acres',
    irrigation: 'Karez (ancient underground water channels), check dams, tube wells (limited)',
    challenges: 'Water scarcity (annual rainfall <200mm across most areas), post-harvest fruit losses (60–80%), limited cold storage, long distances to markets.',
  },
];

// ── Glossary terms ──
const GLOSSARY_TERMS = [
  { slug: 'alternaria-solani', term: 'Alternaria solani', category: 'Pathogen', definition: 'A soil-borne fungal pathogen responsible for early blight disease in tomatoes and potatoes. Produces dark lesions with concentric rings and a characteristic yellow halo on leaves. Spreads by wind and water splash. Member of the Pleosporaceae family.', related: ['early-blight', 'mancozeb', 'fungicide'] },
  { slug: 'bemisia-tabaci', term: 'Bemisia tabaci', category: 'Pest', definition: 'The silverleaf whitefly — a sap-sucking insect pest that is the most destructive insect in cotton production in Pakistan. Adults are 1–1.5mm long with white wings. Transmits over 100 plant viruses. Highly resistant to many insecticide classes.', related: ['whitefly', 'imidacloprid', 'neonicotinoid'] },
  { slug: 'systemic-fungicide', term: 'Systemic Fungicide', category: 'Pesticide Type', definition: 'A fungicide that is absorbed into plant tissues and transported through the vascular system. Unlike contact (protectant) fungicides, systemics provide curative activity by reaching fungal cells inside plant tissue. Examples include triazoles (propiconazole, difenoconazole) and strobilurins (azoxystrobin).', related: ['contact-fungicide', 'triazole', 'dmi-fungicide'] },
  { slug: 'contact-fungicide', term: 'Contact Fungicide', category: 'Pesticide Type', definition: 'A protective fungicide that remains on the plant surface and prevents new spore germination. Does not penetrate plant tissue. Must be applied before infection. Examples: mancozeb, copper oxychloride, propineb (Antracol). Resistance risk is low due to multi-site mode of action.', related: ['systemic-fungicide', 'mancozeb', 'copper-oxychloride'] },
  { slug: 'economic-threshold', term: 'Economic Threshold (ET)', category: 'IPM Concept', definition: 'The pest population level at which control action must be taken to prevent economic damage. Below the ET, pest damage costs less than the cost of treatment. Pakistan\'s PCCC publishes official ETs for major crop pests. For cotton whitefly: 10 nymphs per leaf. For wheat yellow rust: 5% infected leaf area.', related: ['ipm', 'action-threshold', 'pest-scouting'] },
  { slug: 'ipm', term: 'Integrated Pest Management (IPM)', category: 'IPM Concept', definition: 'A science-based approach to pest management that combines biological, cultural, mechanical, and chemical controls to minimize economic damage while protecting the environment and human health. IPM prioritizes non-chemical methods and uses pesticides only as a last resort when pest populations exceed economic thresholds.', related: ['economic-threshold', 'biological-control', 'pheromone-trap'] },
  { slug: 'neonicotinoid', term: 'Neonicotinoid', category: 'Pesticide Class', definition: 'A class of systemic insecticides that act on nicotinic acetylcholine receptors in insects. Highly effective against sucking pests (whitefly, aphids, thrips). Examples used in Pakistan: imidacloprid (Confidor), thiamethoxam (Actara), acetamiprid. Resistance is emerging in Bemisia tabaci populations across Pakistan\'s cotton belt.', related: ['imidacloprid', 'bemisia-tabaci', 'resistance-management'] },
  { slug: 'pheromone-trap', term: 'Pheromone Trap', category: 'IPM Tool', definition: 'A device that uses synthetic insect sex pheromones to lure and trap pest insects, primarily used for monitoring population levels. In Pakistan, pheromone traps are used for cotton pink bollworm (PBW) and spodoptera monitoring. Trap catches above threshold (8 moths/trap/night for PBW) indicate need for chemical intervention.', related: ['ipm', 'economic-threshold', 'bollworm'] },
  { slug: 'triazole', term: 'Triazole Fungicide', category: 'Pesticide Class', definition: 'A class of DMI (Demethylation-Inhibiting) fungicides that block sterol biosynthesis in fungal cells. Highly effective against rusts, smuts, Fusarium, and Alternaria. Pakistan examples: propiconazole (Tilt), difenoconazole (Score), tebuconazole. Single-site mode of action means resistance can develop — rotation with multi-site fungicides is recommended.', related: ['dmi-fungicide', 'systemic-fungicide', 'resistance-management'] },
  { slug: 'resistance-management', term: 'Resistance Management', category: 'IPM Concept', definition: 'Strategies to delay or prevent pesticide resistance in pest and pathogen populations. Key tactics: rotate chemical classes with different modes of action, use full recommended doses, apply only when economic threshold is reached, integrate non-chemical methods. In Pakistan\'s cotton belt, imidacloprid resistance in whitefly populations is a documented major problem.', related: ['ipm', 'economic-threshold', 'neonicotinoid'] },
];

module.exports = { DISEASE_GUIDES, PESTICIDE_CONTENT, FARMING_REGIONS, GLOSSARY_TERMS };
